### ISSUE TITLE
AttributeError: 'MemoryCache' object has no attribute 'get_non_flushed_event_count'

### ISSUE THREAD

**Issue by nazarov-ae** [eht16/python-logstash-async#88]
Hi
After updating the version from 2.7.0 to 2.7.1, an error appeared:
```python
Exception in thread LogProcessingWorker:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 72, in run
    reraise(*_capture_exception())
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 99, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 70, in run
    return old_run_func(self, *a, **kw)
  File "/usr/local/lib/python3.8/site-packages/logstash_async/worker.py", line 91, in run
    self._setup_database()
  File "/usr/local/lib/python3.8/site-packages/logstash_async/worker.py", line 132, in _setup_database
    self._non_flushed_event_count = self._database.get_non_flushed_event_count()
AttributeError: 'MemoryCache' object has no attribute 'get_non_flushed_event_count'
```

https://github.com/eht16/python-logstash-async/commit/b9a12a75a4f6bda98df023ab7e5ca5d16c526c36#commitcomment-127016580

**Comment by arossert** [comment]
I have the same issue after updating to the new version

**Comment by vitalerter** [comment]
Also have it when there is no db defined:

`database_path: None`

**Comment by eht16** [comment]
Fixed in https://github.com/eht16/python-logstash-async/commit/f40e8464e64dea0fe2f21d3abbaf886e84900b7f and released as 2.7.2.

Sorry for the inconvenience.
